<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Manage</title>
		<link rel="stylesheet" href="<?php echo $this->basePath();?>/css/bootstrap.min.css" type="text/css">
		<link rel="stylesheet" href="<?php echo $this->basePath();?>/css/bootstrap.css" type="text/css">
		<link rel="stylesheet" href="<?php echo $this->basePath();?>/manager/css/layout.css" type="text/css">
		<link rel="stylesheet" href="<?php echo $this->basePath();?>/jqueryCalendar/jqueryCalendar.css" type="text/css">

		<script type="text/javascript" src="<?php echo $this->basePath();?>/ckeditor/ckeditor.js"></script>
		<script type="text/javascript" src="<?php echo $this->basePath();?>/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->basePath();?>/js/jquery-1.7.2.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->basePath();?>/js/new.js"></script>

		<script type="text/javascript">
		$(document).ready(function() {
			$("[href]").each(function() {
				var path = window.location.href;
				var url1 = path.substring(path.lastIndexOf('/')+1);
				var url2 = (this.href).substring(path.lastIndexOf('/')+1);
				if (url1 == url2)
					$(this).addClass("selected");
			});
		});
	</script>
	</head>

	<body>
		<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container-fluid">
				<div class="navbar-header">
					<a class="navbar-brand" href="<?php echo $this->basePath();?>/admin/index">Kiểm tra online</a>
				</div>
				<div class="navbar-collapse collapse">
					<?php if (isset($this->admin)) { ?>
						<ul class="nav navbar-nav navbar-right">
							<li class="dropdown">
								<a class="dropdown-toggle" href="#" data-toggle="dropdown" role="button">
									<i class="glyphicon glyphicon-user"></i> <?php echo $this->admin; ?>
								</a>
							</li>
							<li><a href="<?php echo $this->basePath();?>/admin/logout"><i class="glyphicon glyphicon-off"></i> Đăng xuất</a></li>
						</ul>
					<?php } ?>
				</div>
			</div>
		</div>

		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-3 col-md-3 sidebar">
					<ul class="nav nav-sidebar">
						<li><p>Môn học</p></li>
						<li><a href="<?php echo $this->basePath();?>/admin/addsubject"><i class="glyphicon glyphicon-plus"></i> Thêm môn học</a></li>
						<li><a href="<?php echo $this->basePath();?>/admin/viewsubject"><i class="glyphicon glyphicon-list-alt"></i> Danh sách môn học</a></li>
					</ul>
					<ul class="nav nav-sidebar">
						<li><p>Người dùng</p></li>
						<li><a href="<?php echo $this->basePath();?>/admin/viewstudent"><i class="glyphicon glyphicon-user"></i> Danh sách học sinh</a></li>
						<li><a href="<?php echo $this->basePath();?>/admin/viewteacher"><i class="glyphicon glyphicon-user"></i> Danh sách giáo viên</a></li>
						<?php if (isset($this->admin) && ($this->level == 1)) {?>
						<li><a href="<?php echo $this->basePath();?>/admin/newteacher"><i class="glyphicon glyphicon-plus"></i> Tạo tài khoản giáo viên</a></li>
						<?php } ?>
					</ul>
					<ul class="nav nav-sidebar">
						<li><p>Câu hỏi</p></li>
						<li><a href="<?php echo $this->basePath();?>/admin/addquestion"><i class="glyphicon glyphicon-plus"></i> Thêm câu hỏi</a></li>
						<li><a href="<?php echo $this->basePath();?>/admin/viewquestion/1"><i class="glyphicon glyphicon-list-alt"></i> Câu hỏi đúng sai</a></li>
						<li><a href="<?php echo $this->basePath();?>/admin/viewquestion/2"><i class="glyphicon glyphicon-list-alt"></i> Câu hỏi chọn đáp án đúng</a></li>
						<li><a href="<?php echo $this->basePath();?>/admin/viewquestion/3"><i class="glyphicon glyphicon-list-alt"></i> Câu hỏi chọn đáp án đúng nhất</a></li>
					</ul>
					<ul class="nav nav-sidebar">
						<li><p>Thi lại</p></li>
						<li><a href="<?php echo $this->basePath();?>/admin/viewrequire"><i class="glyphicon glyphicon-list-alt"></i> Xem yêu cầu thi lại <?php if ($this->require != 0) echo "(".$this->require.")"; ?></a></li>
					</ul>
				</div>

				<div class="col-sm-9 col-sm-offset-3 col-md-9 col-md-offset-3 main">
					<?php echo $this->content; ?>
				</div>
			</div>
		</div>

	</body>
</html>