<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8"/>
	<title>Manage</title>
	
	<link rel="stylesheet" href="<?php echo $this->basePath();?>/admin/css/layout.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="<?php echo $this->basePath();?>/css/new.css" type="text/css"/>
	<link rel="stylesheet" href="<?php echo $this->basePath();?>/css/bootstrap.css" type="text/css">
	
	<script src="<?php echo $this->basePath();?>/ckeditor/ckeditor.js" type="text/javascript"></script>
	<script src="<?php echo $this->basePath();?>/admin/js/jquery-1.5.2.min.js" type="text/javascript"></script>
	<script src="<?php echo $this->basePath();?>/js/new.js" type="text/javascript"></script>
	<script src="<?php echo $this->basePath();?>/admin/js/hideshow.js" type="text/javascript"></script>
	<script src="<?php echo $this->basePath();?>/admin/js/jquery.tablesorter.min.js" type="text/javascript"></script>
	<script type="text/javascript" src="<?php echo $this->basePath();?>/admin/js/jquery.equalHeight.js"></script>
</head>
<body>
	<header id="header">
		<hgroup>
			<h1 class="site_title"><a href="<?php echo $this->basePath();?>/admin/index">Website Admin</a></h1>
			<h2 class="section_title">Bảng điều khiển</h2>
		</hgroup>
	</header> <!-- end of header bar -->
	<section id="secondary_bar">
		<div class="user">
		<?php if (isset($this->admin)) { ?>
			<p><?php echo $this->admin; ?></p>
			<a class="logout_user" href="<?php echo $this->basePath();?>/admin/logout" title="Đăng xuất"></a>	
		<?php } ?>
			<!-- <a class="logout_user" href="#" title="Logout">Logout</a> -->
		</div>
		<div class="breadcrumbs_container"></div>
	</section><!-- end of secondary bar -->
	<aside id="sidebar" class="column">
		<br>
		<h3>Môn học</h3>
		<ul class="toggle">
			<li class="icn_new_item"><a href="<?php echo $this->basePath();?>/admin/addsubject">Thêm mới</a></li>
			<li class="icn_edit_item"><a href="<?php echo $this->basePath();?>/admin/viewsubject">Danh sách</a></li>
		</ul>
		<br>
		<h3>Người dùng</h3>
		<ul class="toggle">
			<li class="icn_view_users"><a href="<?php echo $this->basePath();?>/admin/viewstudent">Học sinh</a></li>
			<li class="icn_view_users"><a href="<?php echo $this->basePath();?>/admin/viewteacher">Giáo viên</a></li>
		<?php 
			if (isset($this->admin) && ($this->level == 1)) {
		?>
			<li class="icn_add_users"><a href="<?php echo $this->basePath();?>/admin/newteacher">Tạo tài khoản giáo viên</a></li>	
		<?php				
			}
		?>
		</ul>
		<br>
		<h3>Câu hỏi</h3>
		<ul class="toggle">
			<li class="icn_new_item"><a href="<?php echo $this->basePath();?>/admin/addquestion">Thêm mới</a></li>
			<li class="icn_edit_item"><a href="#" onclick="return toggleMe('type_question')">Danh sách</a></li>
				<div id="type_question" style="display:none" class="type_question">
					<li class="icn_categories"><a href="<?php echo $this->basePath();?>/admin/viewquestion/1">Câu hỏi đúng sai</a></li>
					<li class="icn_categories"><a href="<?php echo $this->basePath();?>/admin/viewquestion/2">Câu hỏi lựa chọn đúng</a></li>
					<li class="icn_categories"><a href="<?php echo $this->basePath();?>/admin/viewquestion/3">Câu hỏi lựa chọn đúng nhất</a></li>
				</div>
		</ul>
		<br>
		<h3><a href="<?php echo $this->basePath();?>/admin/viewrequire">Yêu cầu thi lại <?php if ($this->require != 0) echo "(".$this->require.")"; ?></a></h3>
		
		<div class="sidebar_footer">
			<hr />
			<strong>Website Admin</strong>
		</div>
	</aside><!-- end of sidebar -->
	<section id="main" class="column">
		<?php echo $this->content; ?>
	</section>
</body>
</html>