<html>
	<head>
		<meta charset="UTF-8">
		<title>Manage</title>
		<link rel="stylesheet" href="<?php echo $this->basePath();?>/css/bootstrap.min.css" type="text/css">
		<link rel="stylesheet" href="<?php echo $this->basePath();?>/css/bootstrap.css" type="text/css">
		<link rel="stylesheet" href="<?php echo $this->basePath();?>/manager/css/signin.css" type="text/css">
	</head>
	<body>
		<?php echo $this->content; ?>
	</body>

</html>