<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Kiểm tra trực tuyến</title>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/css/bootstrap.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/css/style.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/css/new.css" />
<script src="<?php echo $this->basePath();?>/js/new.js" type="text/javascript"></script>

</head>
<body>
<div id="wrap">
	<div class="header">
       	<div class="logo"><a href="index.html"><img src="<?php echo $this->basePath();?>/images/logo.png" alt="" title="" border="0" /></a></div>            
        <div id="menu">
			<ul>                                                                       
				<li class="selected"><a href="<?php echo $this->basePath();?>/index/index">Trang chủ</a></li>
            	<li><a href="#">Giới thiệu</a></li>
            	<li><a href="<?php echo $this->basePath();?>/index/viewteacher">Giáo viên</a></li>
            	<li><a href="<?php echo $this->basePath();?>/index/viewstudent">Học sinh</a></li>
		<?php 	if (isset($this->student)) { ?>
				<li><a href="<?php echo $this->basePath();?>/student/exam">Bài thi</a></li>
	            
		<?php 	} 
				else { ?>
				<li><a href="<?php echo $this->basePath();?>/index/login">Đăng nhập</a></li>
	            <li><a href="<?php echo $this->basePath();?>/index/register">Đăng ký</a></li>
		<?php 	} ?> 
	            <li><a href="#">Liên hệ</a></li>
			</ul>
        </div>         
	</div> 
          
	<div class="center_content">
		<div class="left_content">
        	<?php echo $this->content; ?>
        </div><!--end of left content-->
        
        <div class="right_content">
        <div class="right_box"> 
		<?php if (isset($this->student)) { ?>
				<div class="about">
					<div class="title"><span class="title_icon"><img src="<?php echo $this->basePath();?>/images/bullet6.png" alt="" title="" /></span>Học sinh</div>
					<div class="info-student">
						<img src="<?php echo $this->basePath();?>/images/no-user.png" class="img-polaroid"/>
						<p><?php echo $this->name ?></p>
						<p>Điểm TB: <?php echo $this->mark ?></p>
						<p><a href="<?php echo $this->basePath();?>/student/logout">Đăng xuất</a></p>
					</div>
	            </div>
		<?php } ?> 
             	<div class="title"><span class="title_icon"><img src="<?php echo $this->basePath();?>/images/bullet3.png" alt="" title="" /></span>Môn học</div> 
                <ul class="list">
                <?php
                	foreach ($this->subject as $item) {
                ?>
                		<li><a href="#"><?php echo $item->subject_name; ?></a></li>
                <?php
                	}
                ?>                        
                </ul>
                <br />       
             	<div class="title"><span class="title_icon"><img src="<?php echo $this->basePath();?>/images/top-student.png" alt="" title="" /></span>Học sinh tiêu biểu</div>  
                <ul class="list">
	            <?php
                	foreach ($this->topStudent as $item) {
                ?>
                		<li><a href="#"><?php echo $item->username; ?></a></li>
                <?php
                	}
                ?>                         
                </ul>      
			</div>         
		</div><!--end of right content-->
               
		<div class="clear"></div>
	</div><!--end of center content-->
        
	<div class="footer"></div>
    
</div>

</body>
</html>