<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Kiểm tra trực tuyến</title>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/css/style.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/css/new.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/jqueryCalendar/jqueryCalendar.css" />

		<script type="text/javascript" src="<?php echo $this->basePath();?>/js/jquery-1.7.2.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->basePath();?>/js/new.js"></script>
		<script type="text/javascript">
			$(document).ready(function() {
				$("[href]").each(function() {
					var path = window.location.href;
					var url1 = path.substring(path.lastIndexOf('/')+1);
					var url2 = (this.href).substring(path.lastIndexOf('/')+1);
					if (url1 == url2)
						$(this).addClass("selected");
				});
			});
		</script>
	</head>
<body>
<div id="wrap">
	<div id="header">
		<div id="logo"><img src="<?php echo $this->basePath();?>/images/logo.png" /></div>
		<div id="menu">
			<ul>
				<li><a href="<?php echo $this->basePath();?>/index/index">Trang chủ</a></li>
				<li><a href="#">Giới thiệu</a></li>
				<li><a href="<?php echo $this->basePath();?>/index/viewteacher">Giáo viên</a></li>
				<li><a href="<?php echo $this->basePath();?>/index/viewstudent">Học sinh</a></li>
		<?php 	if (isset($this->student)) { ?>
				<li><a href="<?php echo $this->basePath();?>/student/exam">Bài thi</a></li>
		<?php 	}
				else { ?>
				<li><a href="<?php echo $this->basePath();?>/index/login">Đăng nhập</a></li>
				<li><a href="<?php echo $this->basePath();?>/index/register">Đăng ký</a></li>
		<?php 	} ?>
				<li><a href="#">Liên hệ</a></li>
			</ul>
		</div>
	</div>

	<div class="center_content">
		<div class="left_content">
			<?php echo $this->content; ?>
		</div><!--end of left content-->

		<div class="right_content">
		<div class="right_box">
		<?php if (isset($this->student)) { ?>
				<div class="about">
					<div class="title"><span class="title_icon"><img src="<?php echo $this->basePath();?>/images/bullet6.png" alt="" title="" /></span>Học sinh</div>
					<div class="info-student">
						<img src="<?php echo $this->basePath();?>/images/no-user.png" class="img-polaroid"/>
						<p><?php echo $this->name ?></p>
						<p>Điểm TB: <?php echo $this->mark ?></p>
						<p><a href="<?php echo $this->basePath();?>/student/logout">Đăng xuất</a></p>
					</div>
				</div>
		<?php } ?>
				<div class="title"><span class="title_icon"><img src="<?php echo $this->basePath();?>/images/bullet3.png" alt="" title="" /></span>Môn học</div>
				<ul class="list">
				<?php
					foreach ($this->subject as $item) {
						$url	= $this->basePath()."/index/viewsubjectinfo/".$item->subject_id;
				?>
					<li><a href="<?php echo $url; ?>"><?php echo $item->subject_name; ?></a></li>
				<?php
					}
				?>
				</ul>
				<br />
				<div class="title"><span class="title_icon"><img src="<?php echo $this->basePath();?>/images/top-student.png" alt="" title="" /></span>Học sinh tiêu biểu</div>
				<ul class="list">
				<?php
					foreach ($this->topStudent as $item) {
				?>
					<li><a href="#"><?php echo $item->username; ?></a></li>
				<?php
					}
				?>
				</ul>
			</div>
		</div><!--end of right content-->

		<div class="clear"></div>
	</div><!--end of center content-->

	<div class="footer"></div>
</div>

</body>
</html>