	<article class="module width_full">
		<div class="title"><span class="title_icon"><img src='<?php echo $this->basePath();?>/images/bullet1.png' /></span>Danh mục tài liệu</div>
		<br><br>
		<div class="exam_frame" style="overflow: auto;">
			<div class="new_prod_box">
				<a href="#">Tin học văn phòng</a>
				<div class="new_prod_bg">
					<a href="#"><img src='<?php echo $this->basePath();?>/images/book/cntt1.jpg' /></a>
				</div>
			</div>
			<div class="new_prod_box">
				<a href="#">Kỹ thuật vi xử lý</a>
				<div class="new_prod_bg">
					<a href="#"><img src='<?php echo $this->basePath();?>/images/book/cntt2.jpg' /></a>
				</div>
			</div>
			<div class="new_prod_box">
				<a href="#">Kỹ nghệ phần mềm</a>
				<div class="new_prod_bg">
					<a href="#"><img src='<?php echo $this->basePath();?>/images/book/cntt3.jpg' /></a>
				</div>
			</div>
			<div class="clear"></div>
			<div class="new_prod_box">
				<a href="#">Cơ sở dữ liệu</a>
				<div class="new_prod_bg">
					<a href="#"><img src='<?php echo $this->basePath();?>/images/book/cntt4.jpg' /></a>
				</div>
			</div>
			<div class="new_prod_box">
				<a href="#">CNTT&TT Việt Nam</a>
				<div class="new_prod_bg">
					<a href="#"><img src='<?php echo $this->basePath();?>/images/book/cntt5.jpg' /></a>
				</div>
			</div>
			<div class="new_prod_box">
				<a href="#">Cơ sở lý thuyết song song</a>
				<div class="new_prod_bg">
					<a href="#"><img src='<?php echo $this->basePath();?>/images/book/cntt6.jpg' /></a>
				</div>
			</div>
			<div class="clear"></div>
			<div class="new_prod_box">
				<a href="#">みんなの日本語 I</a>
				<div class="new_prod_bg">
					<a href="#"><img src='<?php echo $this->basePath();?>/images/book/nihongo1.jpg' /></a>
				</div>
			</div>
			<div class="new_prod_box">
				<a href="#">Mẫu câu tiếng Nhật</a>
				<div class="new_prod_bg">
					<a href="#"><img src='<?php echo $this->basePath();?>/images/book/nihongo4.jpg' /></a>
				</div>
			</div>
			<div class="new_prod_box">
				<a href="#">Từ điển Việt - Nhật</a>
				<div class="new_prod_bg">
					<a href="#"><img src='<?php echo $this->basePath();?>/images/book/nihongo2.jpg' /></a>
				</div>
			</div>
			<div class="clear"></div>
			<div class="new_prod_box">
				<a href="#">Thực hành giao tiếp tiếng Nhật</a>
				<div class="new_prod_bg">
					<a href="#"><img src='<?php echo $this->basePath();?>/images/book/nihongo3.jpg' /></a>
				</div>
			</div>
			<div class="new_prod_box">
				<a href="#">みんなの日本語 II</a>
				<div class="new_prod_bg">
					<a href="#"><img src='<?php echo $this->basePath();?>/images/book/nihongo5.jpg' /></a>
				</div>
			</div>
			<div class="new_prod_box">
				<a href="#">Mẫu câu tiếng Nhật</a>
				<div class="new_prod_bg">
					<a href="#"><img src='<?php echo $this->basePath();?>/images/book/nihongo6.jpg' /></a>
				</div>
			</div>
			<div class="clear"></div>
		</div>
	</article>