<?php
	$form = $this->form;
	$form->prepare();
	$form->setAttribute('action', $this->url('index', array('action' => 'register')));
	$form->get('submit')->setAttribute('class', 'register');
	$form->get('username')->setAttribute('class', 'form-control');
	$form->get('username')->setAttribute('placeholder', 'Tên đăng nhập');
	$form->get('password')->setAttribute('class', 'form-control');
	$form->get('password')->setAttribute('placeholder', 'Mật khẩu');
	$form->get('re_password')->setAttribute('class', 'form-control');
	$form->get('re_password')->setAttribute('placeholder', 'Nhập lại mật khẩu');
	$form->get('yourname')->setAttribute('class', 'form-control');
	$form->get('yourname')->setAttribute('placeholder', 'Họ tên');
	$form->get('birthday')->setAttribute('class', 'form-control');
	$form->get('birthday')->setAttribute('placeholder', 'Ngày, tháng, năm sinh');
	
	$labelUsername	= $this->formLabel($form->get('username'));
	$username	= $this->formInput($form->get('username'));
	$errorUsername	= $this->formElementErrors($form->get('username'));
	
	$labelPassword	= $this->formLabel($form->get('password'));
	$password	= $this->formInput($form->get('password'));
	$errorPassword	= $this->formElementErrors($form->get('password'));
	
	$labelPassword_	= $this->formLabel($form->get('re_password'));
	$password_	= $this->formInput($form->get('re_password'));
	$errorPassword_	= $this->formElementErrors($form->get('re_password'));
	
	$labelYourname	= $this->formLabel($form->get('yourname'));
	$yourname	= $this->formInput($form->get('yourname'));
	$errorYourname	= $this->formElementErrors($form->get('yourname'));
	
	$labelBirthday	= $this->formLabel($form->get('birthday'));
	$birthday	= $this->formInput($form->get('birthday'));
	$errorBirthday	= $this->formElementErrors($form->get('birthday'));
	
	$submit 	= $this->formInput($form->get('submit'));
	echo $this->form()->openTag($this->form);
?>

	<div class="title"><span class="title_icon"><img src="<?php echo $this->basePath();?>/images/bullet1.png" alt="" title="" /></span>Đăng ký</div>
		<div class="contact_form">
			<div class="form_subtitle">Tạo tài khoản</div>
			<table width="400px">
              	<tr>
              		<td><strong><?php echo $labelUsername ?></strong></td>
              		<td><?php echo $username ?></td>
              	</tr>
              	<tr>
              		<td></td>
              		<td><div class="text-error"><?php echo $this->err; echo $errorUsername; ?></div></td>
              	</tr>
              	<tr>
              		<td><strong><?php echo $labelPassword ?></strong></td>
              		<td><?php echo $password ?></td>
              	</tr>
              	<tr>
              		<td></td>
              		<td><div class="text-error"><?php echo $errorPassword ?></div></td>
              	</tr>
              	<tr>
              		<td><strong><?php echo $labelPassword_ ?></strong></td>
              		<td><?php echo $password_ ?></td>
              	</tr>
              	<tr>
              		<td></td>
              		<td><div class="text-error"><?php echo $errorPassword_ ?></div></td>
              	</tr>
              	<tr>
              		<td><strong><?php echo $labelYourname ?></strong></td>
              		<td><?php echo $yourname ?></td>
              	</tr>
              	<tr>
              		<td></td>
              		<td><div class="text-error"><?php echo $errorYourname ?></div></td>
              	</tr>
              	<tr>
              		<td><strong><?php echo $labelBirthday ?></strong></td>
              		<td><?php echo $birthday ?></td>
              	</tr>
              	<tr>
              		<td></td>
              		<td><div class="text-error"><?php echo $errorBirthday ?></div></td>
              	</tr>
              	<tr>
              		<td></td>
              		<td>
              			<div class="text-success"><?php echo $this->success;?></div>
              			<?php echo $submit ?>
              		</td>
              	</tr>
			</table>
		</div>  
<div class="clear"></div>
<?php
	echo $this->form()->closeTag($form);
?>
		
