 <article class="module width_full">
	<div class="title"><span class="title_icon"><img src="<?php echo $this->basePath();?>/images/bullet1.png" alt="" title="" /></span>Danh sách giáo viên</div>
	<br><br>
		<div class="table_layout">
<?php
	if ($this->paginator != null) {
		if (!isset($_GET['page']))
			$count	= 0;
		else 
			$count	= ($_GET['page'] - 1)*$this->perpage;
?> 
		<br>
		<table class="table table-striped">
			<tr>
				<td style="width: 10%"><strong>STT</strong></td>
				<td style="width: 30%"><strong>Tên đăng nhập</strong></td>
				<td style="width: 30%"><strong>Họ tên</strong></td>
				<td style="width: 30"><strong>Ngày sinh</strong></td>
			</tr>
		<?php foreach ($this->paginator as $item) : $count++;?>
			<tr>
	         	<td><?php echo $count?></td>
	            <td><?php echo $this->escapeHtml($item->username);?></td>
	            <td><?php echo $this->escapeHtml($item->name);?></td>
	            <td><?php echo $this->escapeHtml($item->birthday);?></td>
         	</tr>
		<?php endforeach; ?>
		</table>
	<?php }?>
	</div>
</article>
<?php
	$url	= "viewteacher";
	echo $this->paginationControl(
		$this->paginator,
		'sliding',
		array('partial/paginator.phtml', 'Teacher'),
	    array(
			'route' => 'index',
	    	'url'	=> $url,
		)
 	);