<?php
	$mail	= $this->mail;
?>
<h2 class="sub-header" style="font-weight: bold;">Hộp thư</h2>
<dl class="dl-horizontal">
	<dt>Người gửi:</dt>
	<dd><?php echo $mail->name; ?></dd>
	<dt>Email:</dt>
	<dd><?php echo $mail->email; ?></dd>
	<dt>SĐT:</dt>
	<dd><?php echo $mail->phone; ?></dd>
	<dt>Thời gian:</dt>
	<dd><?php echo $mail->created_at; ?></dd>
	<dt>Tiêu đề:</dt>
	<dd><?php echo $mail->title; ?></dd>
	<dt>Nội dung:</dt>
	<dd><?php echo $mail->content; ?></dd>
</dl>
