<?php
	$form	= $this->form;
	$form->prepare();
	$form->setAttribute('action', $this->url('admin', array('action' => 'editsubject', 'id' => $this->id)));
	$form->get('name')->setAttribute('class', 'form-control');
	$form->get('description')->setAttribute('class', 'form-control');
	$form->get('time')->setAttribute('class', 'form-control');
	$form->get('num')->setAttribute('class', 'form-control');
	$form->get('submit')->setAttribute('class', 'btn btn-success');
	
	if ($this->data == null) {
		$form->get('name')->setAttribute('value', $this->subject->subject_name);
		$form->get('description')->setAttribute('value', $this->subject->description);
		$form->get('time')->setAttribute('value', $this->subject->test_time);
		$form->get('num')->setAttribute('value', $this->subject->question_num);
	}
	else {
		$form->get('name')->setAttribute('value', $this->data['name']);
		$form->get('description')->setAttribute('value', $this->data['description']);
		$form->get('time')->setAttribute('value', $this->data['time']);
		$form->get('num')->setAttribute('value', $this->data['num']);
	}
	
	$labelName	= $this->formLabel($form->get('name'));
	$name	= $this->formText($form->get('name'));
	$errorName	= $this->formElementErrors($form->get('name'));
	
	$labelDescription	= $this->formLabel($form->get('description'));
	$description	= $this->formTextarea($form->get('description'));
	$errorDescription	= $this->formElementErrors($form->get('description'));
	
	for ($i	= 10; $i<=90; $i++)
		$arrTime[$i]	= $i;
	$form->get('time')->setOptions(array('value_options' => $arrTime));
	$labelTime	= $this->formLabel($form->get('time'));
	$time	= $this->formSelect($form->get('time'));
	
	for ($i	= 10; $i<=100; $i++)
		$arrNum[$i]	= $i;
	$form->get('num')->setOptions(array('value_options' => $arrNum));
	$labelNum	= $this->formLabel($form->get('num'));
	$num	= $this->formSelect($form->get('num'));
	
	$submit 	= $this->formInput($form->get('submit'));
	echo $this->form()->openTag($this->form);
	
?>

<article class="module width_full">
	<header><h3>Sửa môn học</h3></header>
	<div class="add_data_form">
    	<h3><?php echo $labelName;?></h3>
    	<div class="text-error"><?php echo $errorName;?></div>
    	<p class="text-error"><?php echo $this->err?></p>
    	<?php echo $name;?>
  	</div>
  	<div class="add_data_form">
    	<h3><?php echo $labelDescription;?></h3>
    	<?php echo $description;?>
  	</div>
    <div class="add_data_form">
    	<h3><?php echo $labelTime;?></h3>
    	<?php echo $time;?>
 	</div>
 	 <div class="add_data_form">
    	<h3><?php echo $labelNum;?></h3>
    	<?php echo $num;?>
 	</div>
 	<br>
 	<div class="text-success" align="center"><?php echo $this->success;?></div>
 	<br>
 	<p align="center"><?php echo $submit?></p>
</article>

<?php
	echo $this->form()->openTag($this->form); 
?>