<?php 
	$form	= $this->form;
	$form->prepare();
	$form->setAttribute('action', $this->url('admin', array('action' => 'login')));
	$username	= $this->formInput($form->get('username'));
	$errorUsername	= $this->formElementErrors($form->get('username'));
	$password	= $this->formInput($form->get('password'));
	$errorPassword	= $this->formElementErrors($form->get('password'));
	$submit 	= $this->formInput($form->get('submit'));
	echo $this->form()->openTag($this->form);
?>
	<div class="container form-signin">
		<h2 class="form-signin-heading">Đăng nhập</h2>
		<?php 	
			echo $username;
			echo $errorUsername; 
			echo $password;
			echo $errorPassword;
			echo $this->formHidden($form->get('csrf'));
			if ($this->err != "") echo "<ul class=\"text-danger\"><li>".$this->err."</li></ul>"; 
			echo $submit; 
		?>
	</div> <!-- /container -->
<?php echo $this->form()->closeTag($this->form); ?>
