<h2 class="sub-header" style="font-weight: bold;"><?php echo "Câu hỏi môn ".$this->subjectName;?></h2>
<?php
	if ($this->paginator != null) {
		if (!isset($_GET['page']))
			$count	= 0;
		else 
			$count	= ($_GET['page'] - 1)*$this->perpage;
	}
?>
	<table class="table table-striped">
		<tr align="center">
			<td style="width: 5%"><strong>STT</strong></td>
			<td style="width: 50%"><strong>Nội dung</strong></td>
			<td style="width: 15%"><strong>Loại câu hỏi</strong></td>
			<td style="width: 10%"><strong>Tạo</strong></td>
			<td style="width: 10%"><strong>Cập nhật</strong></td>
			<td style="width: 10%"></td>
		</tr>
	<?php foreach ($this->paginator as $item) : $count++;?>
		<tr>
			<td><?php echo $count?></td>
			<td><?php echo $item->question;?></td>
			<td align="center">
				<?php	
					switch ($item->question_type_id) {
						case 1:
							echo "Chọn đúng sai";
							break;
						case 2:
							echo "Chọn ĐA đúng";
							break;
						case 3:
							echo "Chọn ĐA đúng nhất";
							break;
					}
				?>
			</td>
			<td align="center"><?php echo $item->created_at;?></td>
			<td align="center"><?php echo $item->updated_at;?></td>
			<td align="center">
				<a href="<?php echo $this->basePath()?>/admin/editquestion/<?php echo $item->question_id?>">
					<i class="glyphicon glyphicon-pencil"></i>
				</a>
				<a href="<?php echo $this->basePath()?>/admin/deletequestion/<?php echo $item->question_id?>" Onclick="return ConfirmDelete()">
					<i class="glyphicon glyphicon-trash"></i>
				</a>
			</td>
		</tr>
	<?php endforeach; ?>
	</table>
<?php
	$url	= "questionbysubject/".$this->id;
	echo $this->paginationControl(
		$this->paginator,
		'sliding',
		array('partial/admin/paginator.phtml', 'Question'),
		array(
			'route' => 'admin',
			'url'	=> $url,
		)
	);