<h2 style="font-weight: bold; padding-bottom: 10px;">Danh sách yêu cầu thi lại</h2>
<?php if (count($this->paginator) == 0) {?>
	<p align="center" style="font-size: 16px" class="text-info">Hiện tại không có yêu cầu thi lại nào</p>
<?php } else {
	if ($this->paginator != null) {
		if (!isset($_GET['page']))
			$count	= 0;
		else
			$count	= ($_GET['page'] - 1)*$this->perpage;
	}
?>
	<table class="table table-striped">
		<tr>
			<td style="width: 5%"><strong>STT</strong></td>
			<td style="width: 20%"><strong>Tên sinh viên</strong></td>
			<td style="width: 20%"><strong>Môn thi</strong></td>
			<td style="width: 10"><strong>Điểm</strong></td>
			<td style="width: 20%"><strong>Thời gian</strong></td>
			<td style="width: 12.5%"></td>
			<td style="width: 12.5%"></td>
		</tr>
	<?php foreach ($this->paginator as $item) : $count++;?>
		<tr>
			<td><?php echo $count?></td>
			<td><?php echo $this->arrStudentName[$item->student_id];?></td>
			<td><?php echo $this->arrSubjectName[$item->subject_id];?></td>
			<td><?php echo $item->mark;?></td>
			<td><?php echo $item->updated_at;?></td>
			<td><a href="<?php echo $this->basePath()?>/admin/allowtestagain/<?php echo $item->test_info_id?>"><button class="btn btn-primary" type="button"><i class="glyphicon glyphicon-ok"></i> Đồng ý</button></a></td>
			<td><a href="<?php echo $this->basePath()?>/admin/denytestagain/<?php echo $item->test_info_id?>"><button class="btn btn-danger" type="button"><i class="glyphicon glyphicon-remove"></i> Hủy bỏ</button></a></td>
		</tr>
	<?php endforeach; ?>
	</table>
<?php
	}

	$url	= "viewrequire";
	echo $this->paginationControl(
			$this->paginator,
			'sliding',
			array('partial/admin/paginator.phtml', 'Require'),
			array(
					'route' => 'admin',
					'url'	=> $url,
			)
	);
