<?php
	if ($this->paginator != null) {
		if (!isset($_GET['page']))
			$count	= 0;
		else
			$count	= ($_GET['page'] - 1)*$this->perpage;
?>
	<h2 class="sub-header" style="font-weight: bold;">Danh sách học sinh</h2>
	<table class="table table-striped">
		<tr>
			<td style="width: 5%"><strong>STT</strong></td>
			<td style="width: 20%"><strong>Tên đăng nhập</strong></td>
			<td style="width: 20%"><strong>Họ tên</strong></td>
			<td style="width: 15"><strong>Ngày sinh</strong></td>
			<td style="width: 15%"><strong>Điểm trung bình</strong></td>
			<td style="width: 20%"><strong>Tạo</strong></td>
			<td style="width: 5%"></td>
		</tr>
		<?php foreach ($this->paginator as $item) : $count++;?>
		<tr>
			<td><?php echo $count?></td>
			<td><?php echo $item->username;?></td>
			<td><?php echo $item->name;?></td>
			<td>
				<?php
					$parts = explode('-', $item->birthday);
					$newFormat  = $parts[2]."-".$parts[1]."-".$parts[0];
					echo $newFormat;
				?>
			</td>
			<td align="center"><?php echo $item->average_mark;?></td>
			<td><?php echo $item->created_at;?></td>
			<td align="center">
				<a href="<?php echo $this->basePath()?>/admin/deletestudent/<?php echo $item->student_id?>" Onclick="return ConfirmDelete()">
					<i class="glyphicon glyphicon-trash"></i>
				</a>
			</td>
		</tr>
		<?php endforeach; ?>
		</table>
<?php
	}

	$url	= "viewstudent";
	echo $this->paginationControl(
		$this->paginator,
		'sliding',
		array('partial/admin/paginator.phtml', 'Student'),
		array(
			'route' => 'admin',
			'url'	=> $url,
		)
 	);