<?php
	$student	= $this->student;
?>

<div class="exam_frame">
	<p class="text-uppercase" style="font-size: 18px">Kết quả bài thi</p>
	<dl class="dl-horizontal" style="font-size: 15px">
		<dt>Học sinh</dt>
		<dd class="text-info"><?php echo $student->name; ?></dd>
		<dt>Ngày sinh</dt>
		<dd class="text-info">
		<?php
			$parts = explode('-', $student->birthday);
			$newFormat  = $parts[2]."-".$parts[1]."-".$parts[0];
			echo $newFormat;
		?>
		</dd>
		<dt>Môn thi</dt>
		<dd class="text-info"><?php echo $this->subject; ?></dd>
		<dt>Điểm</dt>
		<dd class="text-info"><?php echo $this->mark; ?></dd>
		<dt>Xếp loại</dt>
		<dd class="text-info"><?php if ($this->mark < 5) echo "Không đạt"; else echo "Đạt"; ?></dd>
	</dl>
	<a href="<?php echo $this->basePath();?>/student/viewanswer">Xem đáp án</a>
</div>
